### ISSUE TITLE
Simplemail does not work with civicrm in a different installation

### ISSUE THREAD

**Issue by jaapjansma** [compucorp/uk.co.compucorp.civicrm.simplemail#1]
We have an installation of CiviCRM in sites/default/modules/civicrm simplemail seems not to work with this installation path.

**Comment by jamienovick** [comment]
hi jaap, forwarding to matt, madura and robin who will take a look.

j

**Comment by jaapjansma** [comment]
Hey @jamienovick I have also provided a fix in a PR.

**Comment by guanhuan** [comment]
@robinmitra Please take a look at this and any other static paths defined in the extension also if any. Thanks.

G
